development:
  adapter: postgresql
  database: jarvis_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: jarvis_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: jarvis_production
  pool: 5
  timeout: 5000